#!/usr/bin/env python3
"""mdc_convert — deterministic Cursor ``.mdc`` → Claude Code converter.

Maps Cursor project rules (``.cursor/rules/**/*.mdc``, legacy ``.cursorrules``)
onto Claude Code's memory surfaces so both editors share one source of truth:

    alwaysApply | globs | description | Cursor type      | Claude Code target
    ------------+-------+-------------+------------------+-------------------------------------------
    true        | any   | any         | Always           | managed block in CLAUDE.md
    false       | set   | any         | Auto Attached    | .claude/rules/<slug>.md  (paths: <globs>)
    false       | unset | set         | Agent Requested  | .claude/skills/<slug>/SKILL.md (name, description)
    false       | unset | unset       | Manual (@rule)   | .claude/skills/<slug>/SKILL.md (invoke /<slug>)
    (config)    |       |             | product spec     | managed block in SPEC.md

Nested rule folders (``<dir>/.cursor/rules/x.mdc``) are scoped to ``<dir>/**``.

Idempotent: generated files carry a provenance comment; managed blocks sit between
``<!-- mdc:begin <slug> … -->`` / ``<!-- mdc:end <slug> -->`` markers under the
``<!-- mdc:managed-section -->`` anchor. Text outside markers is preserved, apart from
newline normalisation (CRLF → LF; runs of three or more newlines collapse to one blank line).
Stale generated outputs (source removed) are pruned. Hand-written ``.claude/rules`` /
skills that lack the provenance ``GEN_MARK`` are never overwritten unless ``--force``.
``--check`` is a CI gate.

Sources (formats verified 2026-09-08 via Context7):
  * Cursor rules: https://cursor.com/docs/rules  (frontmatter: description, globs, alwaysApply)
  * Claude Code memory/rules: https://code.claude.com/docs/en/memory  (.claude/rules, ``paths:``)
  * Claude Code skills: https://code.claude.com/docs/en/slash-commands  (.claude/skills/<name>/SKILL.md)

Stdlib only. Cursor frontmatter is *not* strict YAML (``globs: *.ts`` is common), so a
tolerant parser is used on purpose instead of PyYAML.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

VERSION = "1.0.1"
TOOL = "scripts/mdc_convert.py"
ANCHOR = "<!-- mdc:managed-section -->"
GEN_MARK = "<!-- generated by scripts/mdc_convert.py from "
DEFAULT_CONFIG = {
    "sources": [".cursor/rules"],
    "legacy_cursorrules": True,
    "claude_file": "CLAUDE.md",
    "spec_file": "SPEC.md",
    "rules_dir": ".claude/rules",
    "skills_dir": ".claude/skills",
    "manifest": ".claude/mdc-manifest.json",
    "exclude_dirs": [".git", "node_modules", ".venv", "venv", "__pycache__", ".autoroute-dry", "study"],
    "spec": [],
    "map": {},
    "agent_requested_as": "skill",  # or "rule"
}
TARGETS = ("claude", "rule", "skill", "spec")

# ── frontmatter ──────────────────────────────────────────────────────────────

_FM_RE = re.compile(r"\A\ufeff?---[ \t]*\r?\n(.*?)(?:\r?\n)?---[ \t]*(?:\r?\n|\Z)", re.S)


def _unquote(v: str) -> str:
    v = v.strip()
    if len(v) >= 2 and v[0] == v[-1] and v[0] in "\"'":
        return v[1:-1]
    return v


def _to_bool(v) -> bool | None:
    if isinstance(v, bool):
        return v
    if v is None:
        return None
    s = str(v).strip().lower()
    if s in ("true", "yes", "on", "1"):
        return True
    if s in ("false", "no", "off", "0", ""):
        return False
    return None


def _split_globs(v) -> list[str]:
    """Cursor writes globs as a comma-separated string, a YAML list, or an inline list."""
    if v is None:
        return []
    if isinstance(v, list):
        items = v
    else:
        s = str(v).strip()
        if s.startswith("[") and s.endswith("]"):
            s = s[1:-1]
        items = s.split(",")
    out: list[str] = []
    for it in items:
        g = _unquote(str(it))
        if g:
            out.append(g)
    return out


def parse_frontmatter(text: str) -> tuple[dict, str, bool]:
    """Return (meta, body, had_frontmatter). Tolerant YAML subset: scalars, lists, inline lists."""
    m = _FM_RE.match(text)
    if not m:
        return {}, text, False
    raw = m.group(1)
    body = text[m.end():]
    meta: dict = {}
    key: str | None = None
    for line in raw.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if re.match(r"^\s*-\s*", line) and key is not None:
            item = _unquote(re.sub(r"^\s*-\s*", "", line))
            cur = meta.get(key)
            if cur in (None, ""):
                meta[key] = [item]
            elif isinstance(cur, list):
                cur.append(item)
            else:
                meta[key] = [str(cur), item]
            continue
        km = re.match(r"^([A-Za-z_][A-Za-z0-9_-]*)\s*:\s*(.*)$", line)
        if not km:
            continue  # unknown line shape; ignore rather than fail
        key = km.group(1)
        val = km.group(2).strip()
        if val.startswith("#"):
            val = ""
        if val == "":
            meta[key] = None
        elif val.startswith("[") and val.endswith("]"):
            meta[key] = _split_globs(val)
        else:
            meta[key] = _unquote(val)
    return meta, body, True


# ── model ────────────────────────────────────────────────────────────────────


@dataclass
class Rule:
    source: str            # repo-relative posix path
    slug: str
    scope: str             # "" for root, else "pkg/sub/" prefix
    description: str
    globs: list[str]
    always: bool
    body: str
    sha: str
    cursor_type: str = ""  # always | auto | agent | manual
    target: str = ""       # claude | rule | skill | spec
    out_path: str = ""     # file path for rule/skill; claude_file/spec_file for blocks
    warnings: list[str] = field(default_factory=list)


def slugify(stem: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", stem.lower()).strip("-")
    return s or "rule"


def _norm_body(body: str) -> str:
    body = body.replace("\r\n", "\n").replace("\r", "\n")
    lines = [ln.rstrip() for ln in body.split("\n")]
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    return "\n".join(lines) + ("\n" if lines else "")


def classify(meta: dict, had_fm: bool) -> str:
    always = _to_bool(meta.get("alwaysApply"))
    globs = _split_globs(meta.get("globs"))
    desc = str(meta.get("description") or "").strip()
    if always:
        return "always"
    if globs:
        return "auto"
    if desc:
        return "agent"
    return "manual"


# ── discovery ────────────────────────────────────────────────────────────────


def _rel(root: Path, p: Path) -> str:
    """Repo-relative posix path; sources outside the repo (e.g. ../.cursor/rules) keep '..' segments."""
    return os.path.relpath(p, root).replace(os.sep, "/")


def discover_sources(root: Path, cfg: dict) -> list[Path]:
    excl = set(cfg["exclude_dirs"])
    found: set[Path] = set()
    # 1) configured source dirs (relative to root, or absolute / outside the repo), recursive
    for src in cfg["sources"]:
        d = (root / os.path.expanduser(str(src))).resolve()
        if d.is_dir():
            for p in d.rglob("*.mdc"):
                if not any(part in excl for part in _rel(root, p).split("/")):
                    found.add(p)
    # 2) nested <dir>/.cursor/rules anywhere in the repo
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in excl]
        dp = Path(dirpath)
        if dp.name == "rules" and dp.parent.name == ".cursor":
            for fn in filenames:
                if fn.endswith(".mdc"):
                    found.add(dp / fn)
    # 3) legacy .cursorrules at root
    if cfg.get("legacy_cursorrules"):
        legacy = root / ".cursorrules"
        if legacy.is_file():
            found.add(legacy)
    return sorted(found, key=lambda p: _rel(root, p))


def load_rule(root: Path, path: Path, cfg: dict) -> Rule:
    text = path.read_text(encoding="utf-8", errors="replace")
    rel = _rel(root, path)
    if path.name == ".cursorrules":
        meta, body, had_fm = {"alwaysApply": True}, text, True
        stem = "cursorrules"
    else:
        meta, body, had_fm = parse_frontmatter(text)
        stem = path.stem
    # scope: <dir>/.cursor/rules/<...>/x.mdc → "<dir>/" (never for sources outside the repo)
    scope = ""
    parts = Path(rel).parts
    if ".cursor" in parts and not rel.startswith("..") and not os.path.isabs(rel):
        i = parts.index(".cursor")
        if i > 0:
            scope = "/".join(parts[:i]) + "/"
    body = _norm_body(body)
    sha = hashlib.sha256(text.encode("utf-8")).hexdigest()[:12]
    r = Rule(
        source=rel,
        slug=slugify(stem),
        scope=scope,
        description=str(meta.get("description") or "").strip(),
        globs=_split_globs(meta.get("globs")),
        always=bool(_to_bool(meta.get("alwaysApply"))),
        body=body,
        sha=sha,
    )
    if not had_fm:
        r.warnings.append("no frontmatter → treated as Manual")
    r.cursor_type = classify(meta, had_fm)
    # nested always-apply rules are scoped, so they become path rules
    if r.cursor_type == "always" and scope:
        r.cursor_type = "auto"
        r.globs = [scope + "**"]
        r.warnings.append(f"nested alwaysApply scoped to {scope}**")
    elif scope and r.globs:
        r.globs = [g if g.startswith(scope) else scope + g.lstrip("/") for g in r.globs]
    return r


def assign_targets(rules: list[Rule], cfg: dict) -> None:
    spec_names = set(cfg.get("spec") or [])
    mapping = dict(cfg.get("map") or {})
    agent_as = cfg.get("agent_requested_as", "skill")
    seen: dict[str, int] = {}
    for r in rules:
        # de-duplicate slugs deterministically (sorted by source already)
        n = seen.get(r.slug, 0) + 1
        seen[r.slug] = n
        if n > 1:
            r.warnings.append(f"slug collision → {r.slug}-{n}")
            r.slug = f"{r.slug}-{n}"
        forced = mapping.get(r.slug) or mapping.get(Path(r.source).stem)
        if r.slug in spec_names or Path(r.source).stem in spec_names:
            forced = "spec"
        if forced:
            if forced not in TARGETS:
                raise SystemExit(f"config map: unknown target '{forced}' for {r.slug} (use {TARGETS})")
            r.target = forced
        elif r.cursor_type == "always":
            r.target = "claude"
        elif r.cursor_type == "auto":
            r.target = "rule"
        elif r.cursor_type == "agent":
            r.target = "skill" if agent_as == "skill" else "rule"
        else:
            r.target = "skill"
        if r.target == "rule":
            r.out_path = f"{cfg['rules_dir']}/{r.slug}.md"
        elif r.target == "skill":
            r.out_path = f"{cfg['skills_dir']}/{r.slug}/SKILL.md"
        elif r.target == "claude":
            r.out_path = cfg["claude_file"]
        else:
            r.out_path = cfg["spec_file"]


# ── rendering ────────────────────────────────────────────────────────────────


def _title(r: Rule) -> str:
    return r.description if r.description else r.slug


def _provenance(r: Rule) -> str:
    return f"{GEN_MARK}{r.source} sha256={r.sha}; edit the .mdc, not this file -->"


def render_rule_file(r: Rule) -> str:
    paths = r.globs or ["**"]
    fm = ["---", "paths:"] + [f'  - "{g}"' for g in paths] + ["---"]
    head = "\n".join(fm) + "\n" + _provenance(r) + "\n\n"
    body = r.body
    if not body.lstrip().startswith("#"):
        body = f"# {_title(r)}\n\n" + body
    return head + body


def render_skill_file(r: Rule) -> str:
    desc = r.description or f"Manual Cursor rule {r.slug}; invoke with /{r.slug}"
    desc = desc.replace("\n", " ").strip()
    if any(ch in desc for ch in ":#\"'{}[]") or desc != desc.strip():
        desc = '"' + desc.replace("\\", "\\\\").replace('"', '\\"') + '"'
    head = f"---\nname: {r.slug}\ndescription: {desc}\n---\n{_provenance(r)}\n\n"
    body = r.body or f"# {r.slug}\n\n(empty rule body)\n"
    return head + body


def render_block(r: Rule) -> str:
    title = _title(r)
    body = r.body.rstrip("\n")
    lines = [f"<!-- mdc:begin {r.slug} source={r.source} sha256={r.sha} -->", f"### {title}"]
    if r.cursor_type != "always" or r.globs:
        meta_bits = []
        if r.globs:
            meta_bits.append("globs: " + ", ".join(r.globs))
        if meta_bits:
            lines.append("_" + " · ".join(meta_bits) + "_")
    lines.append("")
    if body:
        lines.append(body)
    lines.append(f"<!-- mdc:end {r.slug} -->")
    return "\n".join(lines)


_BLOCK_RE = re.compile(r"<!-- mdc:begin (?P<slug>[^\s]+)[^\n]*-->\n.*?<!-- mdc:end (?P=slug) -->\n?", re.S)


def merge_managed(existing: str | None, blocks: list[str], section_title: str, create_header: str) -> str | None:
    """Return the new file text, or None when the file should not exist."""
    if existing is None:
        if not blocks:
            return None
        existing = create_header.rstrip("\n") + "\n"
    base = existing.replace("\r\n", "\n")
    base = _BLOCK_RE.sub("", base)
    base = re.sub(r"\n{3,}", "\n\n", base).rstrip("\n") + "\n"
    if ANCHOR not in base:
        if not blocks:
            return base
        base = base.rstrip("\n") + f"\n\n## {section_title}\n\n{ANCHOR}\n"
    idx = base.index(ANCHOR)
    line_end = base.index("\n", idx) + 1 if "\n" in base[idx:] else len(base)
    before, after = base[:line_end], base[line_end:].strip("\n")
    out = before
    if blocks:
        out += "\n" + "\n\n".join(blocks) + "\n"
    if after:
        out += "\n" + after + "\n"
    out = re.sub(r"\n{3,}", "\n\n", out)
    return out


# ── planning ─────────────────────────────────────────────────────────────────


@dataclass
class Plan:
    writes: dict[str, str]          # rel path → content
    deletes: list[str]              # rel paths to remove (stale generated)
    rules: list[Rule]
    notes: list[str]


def _existing_generated(root: Path, cfg: dict) -> set[str]:
    out: set[str] = set()
    for d in (cfg["rules_dir"], cfg["skills_dir"]):
        base = root / d
        if not base.is_dir():
            continue
        for p in base.rglob("*.md"):
            try:
                # GEN_MARK sits after frontmatter; long globs push it past any fixed head.
                text = p.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            if GEN_MARK in text:
                out.add(_rel(root, p))
    return out


def build_plan(root: Path, cfg: dict) -> Plan:
    notes: list[str] = []
    sources = discover_sources(root, cfg)
    rules = [load_rule(root, p, cfg) for p in sources]
    assign_targets(rules, cfg)
    writes: dict[str, str] = {}
    deletes: list[str] = []

    for r in rules:
        for w in r.warnings:
            notes.append(f"{r.source}: {w}")
        if r.target == "rule":
            writes[r.out_path] = render_rule_file(r)
        elif r.target == "skill":
            writes[r.out_path] = render_skill_file(r)

    def _managed(path_key: str, target: str, title: str, header: str) -> None:
        rel = cfg[path_key]
        p = root / rel
        existing = p.read_text(encoding="utf-8", errors="replace") if p.is_file() else None
        blocks = [render_block(r) for r in rules if r.target == target]
        new = merge_managed(existing, blocks, title, header)
        if new is None:
            return
        if existing is None or new != existing:
            writes[rel] = new

    _managed("claude_file", "claude", "Cursor rules (converted by scripts/mdc_convert.py)",
             f"# Project memory\n\n{ANCHOR}\n")
    _managed("spec_file", "spec", "Converted rule specs (scripts/mdc_convert.py)",
             f"# Spec\n\n{ANCHOR}\n")

    # prune stale generated files
    wanted = {r.out_path for r in rules if r.target in ("rule", "skill")}
    for stale in sorted(_existing_generated(root, cfg) - wanted):
        deletes.append(stale)

    manifest_rel = cfg["manifest"]
    if rules:
        manifest = {
            "tool": TOOL,
            "version": VERSION,
            "rules": [
                {
                    "source": r.source,
                    "slug": r.slug,
                    "cursorType": r.cursor_type,
                    "target": r.target,
                    "output": r.out_path,
                    "sha256": r.sha,
                    "alwaysApply": r.always,
                    "globs": r.globs,
                    "description": r.description,
                    "scope": r.scope,
                }
                for r in rules
            ],
        }
        writes[manifest_rel] = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    elif (root / manifest_rel).is_file():
        deletes.append(manifest_rel)

    # drop no-op writes
    for rel in list(writes):
        p = root / rel
        if p.is_file() and p.read_text(encoding="utf-8", errors="replace") == writes[rel]:
            del writes[rel]
    return Plan(writes=writes, deletes=deletes, rules=rules, notes=notes)


def protected_write_conflicts(root: Path, plan: Plan) -> list[str]:
    """Paths where a GEN_MARK-bearing write would clobber a hand-written file.

    Generated rule/skill bodies carry ``GEN_MARK``. Hand-written
    ``.claude/rules/*`` / skills do not. Refusing the write (unless ``--force``)
    preserves those files when a matching ``.mdc`` appears.
    """
    conflicts: list[str] = []
    for rel, content in plan.writes.items():
        if GEN_MARK not in content:
            continue
        p = root / rel
        if not p.is_file():
            continue
        try:
<<<<<<< HEAD
            # GEN_MARK is emitted after frontmatter; globs/descriptions are unbounded,
            # so a fixed head slice misclassifies legitimate generated files.
            existing = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if GEN_MARK not in existing:
=======
            head = p.read_text(encoding="utf-8", errors="replace")[:800]
        except OSError:
            continue
        if GEN_MARK not in head:
>>>>>>> 80f65c0 (Refuse mdc_convert overwrite of hand-written Claude rules.)
            conflicts.append(rel)
    return sorted(conflicts)


def apply_plan(root: Path, plan: Plan, *, force: bool = False) -> None:
    if not force:
        conflicts = protected_write_conflicts(root, plan)
        if conflicts:
            lines = [
                "REFUSING overwrite of hand-written file(s) without GEN_MARK provenance:",
                *[f"  {c}" for c in conflicts],
                "Re-run with --force to overwrite, or rename/remove the hand-written file.",
            ]
            raise SystemExit("\n".join(lines))
    for rel, content in sorted(plan.writes.items()):
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content, encoding="utf-8")
    for rel in plan.deletes:
        p = root / rel
        if p.is_file():
            p.unlink()
            # remove empty skill dirs
            parent = p.parent
            while parent != root and parent.is_dir() and not any(parent.iterdir()):
                parent.rmdir()
                parent = parent.parent


# ── config / cli ─────────────────────────────────────────────────────────────


def load_config(root: Path, explicit: str | None) -> dict:
    cfg = dict(DEFAULT_CONFIG)
    path = root / (explicit or ".mdc-convert.json")
    if path.is_file():
        try:
            user = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise SystemExit(f"{path}: invalid JSON: {exc}")
        for k, v in user.items():
            if k.startswith("_"):
                continue
            if k not in DEFAULT_CONFIG:
                raise SystemExit(f"{path}: unknown key '{k}'")
            cfg[k] = v
    return cfg


def summarize(plan: Plan, root: Path) -> str:
    lines = [f"mdc_convert {VERSION} — root {root}"]
    if not plan.rules:
        lines.append("no .mdc sources found (looked in .cursor/rules/**, nested .cursor/rules, .cursorrules)")
    for r in plan.rules:
        lines.append(f"  {r.source:45s} {r.cursor_type:7s} → {r.target:6s} {r.out_path}")
    for n in plan.notes:
        lines.append(f"  note: {n}")
    for rel in sorted(plan.writes):
        lines.append(f"  write  {rel}")
    for rel in plan.deletes:
        lines.append(f"  delete {rel}")
    if not plan.writes and not plan.deletes:
        lines.append("  outputs up to date")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0], formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=".", help="repo root (default: cwd)")
    ap.add_argument("--config", default=None, help="config JSON (default: .mdc-convert.json if present)")
    ap.add_argument("--src", action="append", default=[], metavar="DIR",
                    help="extra .mdc source dir (repeatable; e.g. ../.cursor/rules for a shared apps/ folder)")
    ap.add_argument("--check", action="store_true", help="exit 1 if outputs are stale (CI gate); writes nothing")
    ap.add_argument("--dry-run", action="store_true", help="print the plan; write nothing")
    ap.add_argument("--force", action="store_true",
                    help="overwrite hand-written .claude/rules or skills that lack GEN_MARK provenance")
    ap.add_argument("--json", action="store_true", help="print the plan as JSON")
    ap.add_argument("--version", action="version", version=VERSION)
    ns = ap.parse_args(argv)

    root = Path(ns.root).resolve()
    if not root.is_dir():
        print(f"error: root {root} is not a directory", file=sys.stderr)
        return 2
    cfg = load_config(root, ns.config)
    if ns.src:
        cfg["sources"] = list(cfg["sources"]) + list(ns.src)
    plan = build_plan(root, cfg)
    conflicts = [] if ns.force else protected_write_conflicts(root, plan)

    if ns.json:
        print(json.dumps({
            "rules": [r.__dict__ for r in plan.rules],
            "writes": sorted(plan.writes),
            "deletes": plan.deletes,
            "notes": plan.notes,
            "conflicts": conflicts,
        }, indent=2, sort_keys=True, default=str))
    else:
        print(summarize(plan, root))
        for c in conflicts:
            print(f"  conflict  {c} (hand-written; needs --force)")

    if conflicts and not ns.dry_run:
        # --check and normal apply both refuse; dry-run only reports
        print(
            "CONFLICT: refusing overwrite of hand-written file(s) without GEN_MARK. "
            "Use --force to overwrite, or rename/remove the hand-written file.",
            file=sys.stderr,
        )
        return 1
    if ns.check:
        if plan.writes or plan.deletes:
            print("STALE: run `python3 scripts/mdc_convert.py` and commit the outputs", file=sys.stderr)
            return 1
        print("OK mdc_convert --check")
        return 0
    if ns.dry_run:
        return 0
    apply_plan(root, plan, force=ns.force)
    print(f"OK mdc_convert ({len(plan.writes)} written, {len(plan.deletes)} pruned)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
